#!/usr/bin/env python3
"""
LoRA Training Dataset Preparation for AI Influencer Pipeline
=============================================================

Prepares training datasets for kohya_ss LoRA training from master images:
  - Organises master images into the correct directory structure
  - Generates caption (.txt) files from character persona data
  - Creates the kohya_ss training configuration TOML
  - Sets up regularisation image directories
  - Supports batch preparation for all 21 characters

Expects master images to have been generated by Phase 1 of the orchestrator.

Usage:
    python prepare_lora_training.py --character aria_nova
    python prepare_lora_training.py --all
    python prepare_lora_training.py --character aria_nova --master-dir output/master_images/aria_nova

Dependencies:
    - characters/personas.json character database
    - config/lora_training_config.json training configuration
    - Pillow for image validation
"""

import argparse
import json
import logging
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import toml
except ImportError:
    toml = None  # type: ignore[assignment]

try:
    from PIL import Image
except ImportError:
    Image = None  # type: ignore[assignment, misc]

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(PROJECT_ROOT))

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_FORMAT = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
logging.basicConfig(level=logging.INFO, format=LOG_FORMAT)
logger = logging.getLogger("prepare_lora")

# ---------------------------------------------------------------------------
# Default paths
# ---------------------------------------------------------------------------
PERSONAS_PATH = PROJECT_ROOT / "characters" / "personas.json"
LORA_CONFIG_PATH = PROJECT_ROOT / "config" / "lora_training_config.json"
MASTER_IMAGES_DIR = PROJECT_ROOT / "output" / "master_images"
LORA_DATASETS_DIR = PROJECT_ROOT / "output" / "lora_datasets"
LORA_MODELS_DIR = PROJECT_ROOT / "output" / "lora_models"
REG_IMAGES_DIR = PROJECT_ROOT / "output" / "reg_images"

# Supported image extensions
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_json(path: Path) -> Dict:
    """Load a JSON file and return its contents."""
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def load_personas(path: Path = PERSONAS_PATH) -> Dict:
    """Load the character personas database."""
    return load_json(path)


def load_lora_config(path: Path = LORA_CONFIG_PATH) -> Dict:
    """Load the LoRA training configuration."""
    return load_json(path)


def get_character_slugs(personas: Dict) -> List[str]:
    """Return sorted list of all character slugs."""
    characters = personas.get("characters", personas)
    if isinstance(characters, list):
        return sorted([c.get("slug", c.get("id", "")) for c in characters])
    if isinstance(characters, dict):
        return sorted(characters.keys())
    return []


def get_character(personas: Dict, slug: str) -> Dict:
    """Retrieve a single character's data by slug."""
    characters = personas.get("characters", personas)
    if isinstance(characters, list):
        for c in characters:
            if c.get("slug") == slug or c.get("id") == slug:
                return c
        raise KeyError(f"Character '{slug}' not found")
    if isinstance(characters, dict):
        if slug in characters:
            return characters[slug]
        raise KeyError(f"Character '{slug}' not found")
    raise ValueError("Unexpected personas format")


def find_images(directory: Path) -> List[Path]:
    """Find all image files in a directory (non-recursive)."""
    if not directory.exists():
        return []
    images = []
    for f in sorted(directory.iterdir()):
        if f.is_file() and f.suffix.lower() in IMAGE_EXTENSIONS:
            images.append(f)
    return images


def validate_image(path: Path, min_size: int = 512) -> bool:
    """
    Validate that an image file is readable and meets minimum size requirements.

    Returns True if the image is valid, False otherwise.
    """
    if Image is None:
        # Pillow not available; skip validation
        return path.exists() and path.stat().st_size > 0

    try:
        with Image.open(path) as img:
            w, h = img.size
            if w < min_size or h < min_size:
                logger.warning(
                    "Image %s is too small (%dx%d, minimum %d). Consider regenerating.",
                    path.name, w, h, min_size
                )
                return False
            return True
    except Exception as exc:
        logger.error("Cannot read image %s: %s", path, exc)
        return False


# ---------------------------------------------------------------------------
# Caption generation
# ---------------------------------------------------------------------------

def generate_caption(
    character: Dict,
    lora_config: Dict,
    image_index: int = 0,
) -> str:
    """
    Generate a caption string for a training image based on persona data.

    The caption follows the template from lora_training_config.json and includes
    the trigger word, character attributes, and style tags.

    Parameters
    ----------
    character : dict
        Character persona data.
    lora_config : dict
        LoRA training configuration (contains caption template settings).
    image_index : int
        Index of the image (for potential variation in captions).

    Returns
    -------
    str
        The caption string.
    """
    caption_cfg = lora_config.get("caption", {})
    template = caption_cfg.get(
        "template",
        "{trigger_word}, {ethnicity} {gender}, {hair_description}, "
        "{eye_color} eyes, {distinguishing_features}, {style_tags}"
    )
    separator = caption_cfg.get("tag_separator", ", ")
    max_tags = caption_cfg.get("max_tags", 30)

    # Extract character attributes with safe defaults
    slug = character.get("slug", character.get("id", "character"))
    trigger_word = character.get("trigger_word", slug)

    # Physical attributes
    physical = character.get("physical", character.get("appearance", {}))
    ethnicity = physical.get("ethnicity", character.get("ethnicity", ""))
    gender = physical.get("gender", character.get("gender", "woman"))
    hair_description = physical.get("hair", character.get("hair", ""))
    eye_color = physical.get("eye_color", character.get("eye_color", ""))
    distinguishing_features = physical.get(
        "distinguishing_features",
        character.get("distinguishing_features", "")
    )

    # Handle list-type features
    if isinstance(distinguishing_features, list):
        distinguishing_features = separator.join(distinguishing_features)
    if isinstance(hair_description, dict):
        hair_parts = []
        if "color" in hair_description:
            hair_parts.append(hair_description["color"])
        if "style" in hair_description:
            hair_parts.append(hair_description["style"])
        if "length" in hair_description:
            hair_parts.append(hair_description["length"])
        hair_description = " ".join(hair_parts)

    # Style tags
    style_tags_raw = character.get("style_tags", character.get("tags", []))
    if isinstance(style_tags_raw, list):
        style_tags = separator.join(style_tags_raw[:max_tags])
    else:
        style_tags = str(style_tags_raw)

    # Build caption from template
    caption = template.format(
        trigger_word=trigger_word,
        ethnicity=ethnicity,
        gender=gender,
        hair_description=hair_description,
        eye_color=eye_color,
        distinguishing_features=distinguishing_features,
        style_tags=style_tags,
    )

    # Clean up: remove double commas, extra spaces
    while ",," in caption:
        caption = caption.replace(",,", ",")
    while "  " in caption:
        caption = caption.replace("  ", " ")
    caption = caption.strip().strip(",").strip()

    # Enforce max tag count
    tags = [t.strip() for t in caption.split(",") if t.strip()]
    if len(tags) > max_tags:
        tags = tags[:max_tags]
    caption = separator.join(tags)

    return caption


# ---------------------------------------------------------------------------
# Training config TOML generation
# ---------------------------------------------------------------------------

def generate_training_toml(
    character: Dict,
    lora_config: Dict,
    dataset_dir: Path,
    output_dir: Path,
    reg_dir: Optional[Path] = None,
) -> str:
    """
    Generate a kohya_ss training configuration TOML file content.

    Parameters
    ----------
    character : dict
        Character persona data.
    lora_config : dict
        LoRA training configuration.
    dataset_dir : Path
        Path to the prepared training image directory.
    output_dir : Path
        Path where the trained LoRA will be saved.
    reg_dir : Path or None
        Path to regularisation images (if enabled).

    Returns
    -------
    str
        TOML-formatted configuration string.
    """
    training = lora_config.get("training", {})
    dataset = lora_config.get("dataset", {})
    model_cfg = lora_config.get("model", {})
    output_cfg = lora_config.get("output", {})
    reg_cfg = lora_config.get("regularization", {})

    slug = character.get("slug", character.get("id", "character"))
    trigger_word = character.get("trigger_word", slug)
    num_repeats = dataset.get("num_repeats", 50)

    # The image directory name follows kohya_ss convention: {num_repeats}_{trigger_word}
    img_folder_name = f"{num_repeats}_{trigger_word}"

    # Build TOML structure
    output_name = output_cfg.get("output_name_template", "{character_slug}_lora_v1").format(
        character_slug=slug
    )

    # Manual TOML building (avoids strict toml library dependency)
    lines = [
        "[general]",
        f'enable_bucket = {str(dataset.get("enable_bucket", True)).lower()}',
        f'shuffle_caption = {str(dataset.get("shuffle_caption", True)).lower()}',
        f'caption_extension = "{lora_config.get("caption", {}).get("extension", ".txt")}"',
        f'keep_tokens = {dataset.get("keep_tokens", 1)}',
        "",
        "[[datasets]]",
        f'resolution = {dataset.get("resolution", 1024)}',
        f'batch_size = {training.get("train_batch_size", 2)}',
        f'min_bucket_reso = {dataset.get("min_bucket_reso", 512)}',
        f'max_bucket_reso = {dataset.get("max_bucket_reso", 2048)}',
        f'bucket_reso_steps = {dataset.get("bucket_reso_steps", 64)}',
        f'bucket_no_upscale = {str(dataset.get("bucket_no_upscale", True)).lower() if "bucket_no_upscale" in dataset else str(training.get("bucket_no_upscale", True)).lower()}',
        "",
        "  [[datasets.subsets]]",
        f'  image_dir = "{dataset_dir / img_folder_name}"',
        f'  num_repeats = {num_repeats}',
        f'  class_tokens = "{trigger_word}"',
        f'  flip_aug = {str(dataset.get("flip_aug", False)).lower()}',
        f'  color_aug = {str(dataset.get("color_aug", False)).lower()}',
        f'  random_crop = {str(dataset.get("random_crop", False)).lower()}',
    ]

    # Add regularisation subset if enabled
    if reg_cfg.get("enabled", False) and reg_dir and reg_dir.exists():
        reg_repeats = reg_cfg.get("num_repeats", 1)
        class_prompt = reg_cfg.get("class_prompt", "a person")
        reg_folder_name = f"{reg_repeats}_{class_prompt.replace(' ', '_')}"
        lines.extend([
            "",
            "  [[datasets.subsets]]",
            f'  image_dir = "{reg_dir / reg_folder_name}"',
            f'  num_repeats = {reg_repeats}',
            f'  class_tokens = "{class_prompt}"',
            '  is_reg = true',
        ])

    model_type = model_cfg.get("model_type", "flux")
    is_flux = model_type == "flux"

    lines.extend([
        "",
        "[training_arguments]",
        f'pretrained_model_name_or_path = "{model_cfg.get("pretrained_model", "models/unet/z_image_bf16.safetensors")}"',
        f'output_dir = "{output_dir}"',
        f'output_name = "{output_name}"',
        f'save_model_as = "{training.get("save_model_as", "safetensors")}"',
        f'max_train_steps = {training.get("max_train_steps", 1500)}',
        f'save_every_n_steps = {training.get("save_every_n_steps", 500)}',
        f'learning_rate = {training.get("learning_rate", 5e-5)}',
        f'unet_lr = {training.get("unet_lr", 5e-5)}',
        f'text_encoder_lr = {training.get("text_encoder_lr", 1e-5)}',
        f'optimizer_type = "{training.get("optimizer_type", "prodigy")}"',
        f'lr_scheduler = "{training.get("lr_scheduler", "cosine_with_restarts")}"',
        f'lr_warmup_steps = {training.get("lr_warmup_steps", 100)}',
        f'lr_scheduler_num_cycles = {training.get("lr_scheduler_num_cycles", 3)}',
        f'network_dim = {training.get("network_dim", 16)}',
        f'network_alpha = {training.get("network_alpha", 8)}',
        f'mixed_precision = "{training.get("mixed_precision", "bf16")}"',
        f'full_bf16 = {str(training.get("full_bf16", True)).lower()}',
        f'gradient_checkpointing = {str(training.get("gradient_checkpointing", True)).lower()}',
        f'gradient_accumulation_steps = {training.get("gradient_accumulation_steps", 1)}',
        f'max_token_length = {training.get("max_token_length", 512)}',
        f'seed = {training.get("seed", 42)}',
        f'cache_latents = {str(training.get("cache_latents", True)).lower()}',
        f'cache_latents_to_disk = {str(training.get("cache_latents_to_disk", False)).lower()}',
        f'cache_text_encoder_outputs = {str(training.get("cache_text_encoder_outputs", True)).lower()}',
        f'noise_offset = {training.get("noise_offset", 0.0357)}',
        f'adaptive_noise_scale = {training.get("adaptive_noise_scale", 0.00357)}',
        f'min_snr_gamma = {training.get("min_snr_gamma", 5)}',
    ])

    # Flux uses SDPA, SDXL uses xformers
    if is_flux:
        if training.get("sdpa", True):
            lines.append(f'sdpa = true')
    else:
        lines.append(f'xformers = {str(training.get("xformers", True)).lower()}')
        lines.append(f'clip_skip = {training.get("clip_skip", 2)}')

    # Optimizer arguments
    opt_args = training.get("optimizer_args", {})
    if opt_args:
        opt_parts = []
        for k, v in opt_args.items():
            if isinstance(v, bool):
                opt_parts.append(f"{k}={str(v).lower()}")
            elif isinstance(v, str):
                opt_parts.append(f'{k}="{v}"')
            else:
                opt_parts.append(f"{k}={v}")
        lines.append(f'optimizer_args = [{", ".join(repr(p) for p in opt_parts)}]')

    # VAE and CLIP paths
    vae_path = model_cfg.get("vae", "")
    if vae_path:
        lines.append(f'vae = "{vae_path}"')
    clip_path = model_cfg.get("clip", "")
    if clip_path:
        lines.append(f'clip_l = "{clip_path}"')

    # Sample generation during training
    sample_steps = output_cfg.get("sample_every_n_steps", 500)
    sample_prompts = output_cfg.get("sample_prompts_file", "")
    if sample_prompts:
        lines.append(f'sample_every_n_steps = {sample_steps}')
        lines.append(f'sample_prompts = "{sample_prompts}"')
        lines.append(f'sample_sampler = "{output_cfg.get("sample_sampler", "sa_solver")}"')

    # Logging
    log_dir = output_cfg.get("log_dir", "output/logs/lora_training")
    lines.append(f'logging_dir = "{log_dir}"')
    lines.append(f'log_prefix = "{slug}_"')

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Dataset preparation
# ---------------------------------------------------------------------------

def prepare_dataset_for_character(
    character: Dict,
    lora_config: Dict,
    master_dir: Path,
    output_dir: Path,
    reg_dir: Optional[Path] = None,
) -> Path:
    """
    Prepare a complete LoRA training dataset for a single character.

    Steps:
      1. Validate and copy master images into kohya_ss directory structure
      2. Generate caption files for each image
      3. Create the training configuration TOML
      4. Set up regularisation images (if enabled)

    Parameters
    ----------
    character : dict
        Character persona data.
    lora_config : dict
        LoRA training configuration.
    master_dir : Path
        Directory containing the character's master images.
    output_dir : Path
        Destination directory for the prepared dataset.
    reg_dir : Path or None
        Source directory for regularisation images.

    Returns
    -------
    Path
        Path to the generated training TOML config file.
    """
    slug = character.get("slug", character.get("id", "character"))
    trigger_word = character.get("trigger_word", slug)
    dataset_cfg = lora_config.get("dataset", {})
    num_repeats = dataset_cfg.get("num_repeats", 50)

    logger.info("Preparing dataset for character: %s", slug)

    # -- Step 1: Validate master images --
    source_images = find_images(master_dir)
    expected_count = dataset_cfg.get("images_per_character", 3)

    if len(source_images) == 0:
        raise FileNotFoundError(
            f"No images found in {master_dir}. "
            f"Run 'orchestrator.py generate-masters --character {slug}' first."
        )

    if len(source_images) < expected_count:
        logger.warning(
            "Found %d images for %s, expected %d. Proceeding with available images.",
            len(source_images), slug, expected_count
        )

    # Validate images
    valid_images = []
    for img_path in source_images:
        if validate_image(img_path, min_size=dataset_cfg.get("resolution", 1024) // 2):
            valid_images.append(img_path)
        else:
            logger.warning("Skipping invalid image: %s", img_path)

    if not valid_images:
        raise ValueError(f"No valid images found for character {slug}")

    logger.info("  Found %d valid master images", len(valid_images))

    # -- Step 2: Create dataset directory structure --
    # kohya_ss expects: dataset_dir/{num_repeats}_{trigger_word}/image.png
    img_folder_name = f"{num_repeats}_{trigger_word}"
    img_dest_dir = output_dir / img_folder_name
    img_dest_dir.mkdir(parents=True, exist_ok=True)

    # Copy images with standardised names
    for idx, src_img in enumerate(valid_images):
        ext = src_img.suffix.lower()
        dest_name = f"{slug}_{idx:03d}{ext}"
        dest_path = img_dest_dir / dest_name
        shutil.copy2(src_img, dest_path)
        logger.info("  Copied: %s -> %s", src_img.name, dest_name)

    # -- Step 3: Generate caption files --
    caption_ext = lora_config.get("caption", {}).get("extension", ".txt")

    for idx in range(len(valid_images)):
        ext = valid_images[idx].suffix.lower()
        img_name = f"{slug}_{idx:03d}{ext}"
        caption_name = f"{slug}_{idx:03d}{caption_ext}"
        caption_path = img_dest_dir / caption_name

        caption_text = generate_caption(character, lora_config, image_index=idx)
        caption_path.write_text(caption_text, encoding="utf-8")
        logger.info("  Caption: %s -> %s", img_name, caption_name)

    # -- Step 4: Set up regularisation images --
    reg_cfg = lora_config.get("regularization", {})
    reg_dest_dir = None

    if reg_cfg.get("enabled", False):
        class_prompt = reg_cfg.get("class_prompt", "a person")
        reg_repeats = reg_cfg.get("num_repeats", 1)
        reg_folder_name = f"{reg_repeats}_{class_prompt.replace(' ', '_')}"
        reg_dest_dir = output_dir / reg_folder_name

        if reg_dir and reg_dir.exists():
            reg_dest_dir.mkdir(parents=True, exist_ok=True)
            reg_images = find_images(reg_dir)

            if reg_images:
                for idx, src_img in enumerate(reg_images):
                    ext = src_img.suffix.lower()
                    dest_path = reg_dest_dir / f"reg_{idx:04d}{ext}"
                    shutil.copy2(src_img, dest_path)

                logger.info(
                    "  Regularisation: copied %d images to %s",
                    len(reg_images), reg_dest_dir
                )
            else:
                logger.warning(
                    "  Regularisation enabled but no images found in %s", reg_dir
                )
                logger.warning(
                    "  Add generic person images to %s for better training results",
                    reg_dir,
                )
        else:
            reg_dest_dir.mkdir(parents=True, exist_ok=True)
            logger.warning(
                "  Regularisation enabled but source dir %s not found. "
                "Created empty directory: %s",
                reg_dir, reg_dest_dir,
            )
            logger.warning(
                "  Add 10-20 generic person images to %s before training",
                reg_dest_dir,
            )

    # -- Step 5: Generate training TOML --
    lora_output_dir = LORA_MODELS_DIR
    lora_output_dir.mkdir(parents=True, exist_ok=True)

    toml_content = generate_training_toml(
        character=character,
        lora_config=lora_config,
        dataset_dir=output_dir,
        output_dir=lora_output_dir,
        reg_dir=output_dir if reg_dest_dir else None,
    )

    toml_path = output_dir / f"{slug}_training_config.toml"
    toml_path.write_text(toml_content, encoding="utf-8")
    logger.info("  Training config: %s", toml_path)

    # -- Step 6: Create a sample prompts file for training preview --
    sample_prompts_path = output_dir / f"{slug}_sample_prompts.txt"
    sample_lines = [
        f"{trigger_word}, portrait photo, studio lighting, high quality --n low quality, blurry",
        f"{trigger_word}, full body photo, natural lighting, urban background --n low quality, distorted",
        f"{trigger_word}, close-up portrait, soft lighting, neutral background --n blurry, watermark",
    ]
    sample_prompts_path.write_text("\n".join(sample_lines) + "\n", encoding="utf-8")
    logger.info("  Sample prompts: %s", sample_prompts_path)

    # -- Summary --
    logger.info("  Dataset preparation complete for %s:", slug)
    logger.info("    Images: %d (in %s)", len(valid_images), img_dest_dir)
    logger.info("    Captions: %d .txt files", len(valid_images))
    logger.info("    Config: %s", toml_path)
    logger.info(
        "    Output LoRA will be: %s/%s_lora_v1.safetensors",
        lora_output_dir, slug,
    )

    return toml_path


def prepare_all_characters(
    personas: Dict,
    lora_config: Dict,
    master_base_dir: Path = MASTER_IMAGES_DIR,
    output_base_dir: Path = LORA_DATASETS_DIR,
    reg_dir: Optional[Path] = REG_IMAGES_DIR,
) -> List[Path]:
    """
    Prepare LoRA training datasets for all characters.

    Returns a list of paths to the generated TOML config files.
    """
    slugs = get_character_slugs(personas)
    logger.info("Preparing datasets for %d characters...", len(slugs))

    toml_paths = []
    errors = []

    for slug in slugs:
        try:
            character = get_character(personas, slug)
            master_dir = master_base_dir / slug
            output_dir = output_base_dir / slug

            toml_path = prepare_dataset_for_character(
                character=character,
                lora_config=lora_config,
                master_dir=master_dir,
                output_dir=output_dir,
                reg_dir=reg_dir,
            )
            toml_paths.append(toml_path)
        except Exception as exc:
            logger.error("Failed to prepare dataset for %s: %s", slug, exc)
            errors.append((slug, str(exc)))

    logger.info("")
    logger.info("=" * 60)
    logger.info("Batch preparation complete:")
    logger.info("  Successful: %d / %d", len(toml_paths), len(slugs))
    if errors:
        logger.warning("  Failed: %d", len(errors))
        for slug, err in errors:
            logger.warning("    - %s: %s", slug, err)
    logger.info("=" * 60)

    # Generate a batch training script
    if toml_paths:
        batch_script = generate_batch_training_script(toml_paths, output_base_dir, lora_config)
        logger.info("Batch training script: %s", batch_script)

    return toml_paths


def generate_batch_training_script(
    toml_paths: List[Path],
    output_dir: Path,
    lora_config: Optional[Dict[str, Any]] = None,
) -> Path:
    """
    Generate a bash script that trains all LoRAs sequentially.

    Parameters
    ----------
    toml_paths : list of Path
        Paths to the TOML training configs.
    output_dir : Path
        Directory to write the batch script.
    lora_config : dict, optional
        LoRA training config (used to determine model type).

    Returns
    -------
    Path
        Path to the generated batch training script.
    """
    # Determine training script based on model type
    model_type = "flux"
    if lora_config:
        model_type = lora_config.get("model", {}).get("model_type", "flux")
    train_script = "flux_train_network.py" if model_type == "flux" else "sdxl_train_network.py"

    script_path = output_dir / "train_all_loras.sh"
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated batch LoRA training script",
        "# Run this after verifying datasets are correct",
        "#",
        "# Usage: bash train_all_loras.sh",
        "#",
        "# Requires: kohya_ss sd-scripts installed and accessible",
        f"# Model type: {model_type} (Z-Image Base / Flux architecture)",
        "# Optimised for RTX 5090 (32GB VRAM, bf16)",
        "",
        'set -euo pipefail',
        "",
        'KOHYA_DIR="${KOHYA_DIR:-/path/to/kohya_ss/sd-scripts}"',
        'ACCELERATE_CMD="accelerate launch"',
        "",
        'echo "Starting batch LoRA training..."',
        'echo "Using kohya_ss at: ${KOHYA_DIR}"',
        'echo ""',
        "",
    ]

    for idx, toml_path in enumerate(toml_paths, 1):
        name = toml_path.stem.replace("_training_config", "")
        lines.extend([
            f'echo "=== Training {idx}/{len(toml_paths)}: {name} ==="',
            f'${{ACCELERATE_CMD}} --mixed_precision bf16 \\',
            f'  "${{KOHYA_DIR}}/{train_script}" \\',
            f'  --config_file "{toml_path}"',
            f'echo "{name} training complete."',
            'echo ""',
            "",
        ])

    lines.extend([
        'echo "All LoRA training complete!"',
        f'echo "Models saved to: {LORA_MODELS_DIR}"',
    ])

    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    script_path.chmod(0o755)
    return script_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prepare LoRA training datasets for AI Influencer characters",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --character aria_nova
  %(prog)s --all
  %(prog)s --character aria_nova --master-dir /path/to/masters
  %(prog)s --all --output-dir /custom/output
        """,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--character",
        type=str,
        help="Character slug to prepare",
    )
    group.add_argument(
        "--all",
        action="store_true",
        help="Prepare datasets for all characters",
    )
    parser.add_argument(
        "--master-dir",
        type=Path,
        default=None,
        help="Override master images directory (for single character mode)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Override output dataset directory",
    )
    parser.add_argument(
        "--personas",
        type=Path,
        default=PERSONAS_PATH,
        help=f"Path to personas.json (default: {PERSONAS_PATH})",
    )
    parser.add_argument(
        "--lora-config",
        type=Path,
        default=LORA_CONFIG_PATH,
        help=f"Path to lora_training_config.json (default: {LORA_CONFIG_PATH})",
    )
    parser.add_argument(
        "--reg-dir",
        type=Path,
        default=REG_IMAGES_DIR,
        help=f"Path to regularisation images (default: {REG_IMAGES_DIR})",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable debug logging",
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # Load configs
    logger.info("Loading personas from %s", args.personas)
    personas = load_personas(args.personas)

    logger.info("Loading LoRA config from %s", args.lora_config)
    lora_config = load_lora_config(args.lora_config)

    if args.all:
        # Batch mode: prepare all characters
        output_dir = args.output_dir or LORA_DATASETS_DIR
        prepare_all_characters(
            personas=personas,
            lora_config=lora_config,
            master_base_dir=MASTER_IMAGES_DIR,
            output_base_dir=output_dir,
            reg_dir=args.reg_dir,
        )
    else:
        # Single character mode
        slug = args.character
        character = get_character(personas, slug)
        master_dir = args.master_dir or (MASTER_IMAGES_DIR / slug)
        output_dir = args.output_dir or (LORA_DATASETS_DIR / slug)

        toml_path = prepare_dataset_for_character(
            character=character,
            lora_config=lora_config,
            master_dir=master_dir,
            output_dir=output_dir,
            reg_dir=args.reg_dir,
        )

        model_type = lora_config.get("model", {}).get("model_type", "flux")
        train_script = "flux_train_network.py" if model_type == "flux" else "sdxl_train_network.py"
        logger.info("")
        logger.info("Done! To start training:")
        logger.info(
            "  accelerate launch --mixed_precision bf16 "
            "/path/to/kohya_ss/sd-scripts/%s "
            "--config_file %s",
            train_script,
            toml_path,
        )


if __name__ == "__main__":
    main()
